select
    shipmentIdentifier as shipment_identifier,
    shipmentType as shipment_type,
    "shipFromLocation.locationIdentifier" as shipment_from_location_identifier,
    "shipToLocation.locationIdentifier" as shipment_to_location_identifier,
    "vendor.organizationIdentifier" as vendor_organization_identifier,
    "buyer.organizationIdentifier" as buyer_organization_identifier,
    "carrier.organizationIdentifier" as carrier_organization_identifier,
    status,
    dateCreated as date_created,
    requestedTimeOfArrival as requested_time_of_arrival,
    committedTimeOfArrival as committed_time_of_arrival,
    actualShipDate as actual_ship_date,
    estimatedTimeOfArrival as estimated_time_of_arrival,
    revisedEstimatedTimeOfArrival as revised_estimated_time_of_arrival,
    predictedTimeOfArrival as predicted_time_of_arrival,
    actualTimeOfArrival as actual_time_of_arrival,
    lineCount as line_count,
    weight,
    weightUnits as weight_units,
    currentLocationCoordinates as current_location_coordinates,
    currentRegion as current_region,
    transportMode as transport_mode,
    houseAirwayBill as house_airway_bill,
    parcelTrackingNumber as parcel_tracking_number,
    airwayMasterNumber as airway_master_number,
    billOfLadingNumber as bill_of_lading_number,
    proNumber as pro_number,
    manifest,
    exclude,
    sourceLink as source_link
from read_csv_auto('data/Shipment_v4_clean.csv', header = true)
